spring:
  application:
    name: cmiMock
  datasource:
    url: jdbc:postgresql://localhost:5432/cmi
    username: postgres
    password: postgres
    testwhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        
date:
  format: YYYYMMddhhmmss   
  
security:
  hash:
    secret: secret
    
server:
  port: 9000