insert into biller (biller_name, biller_code, biller_description, logo_path, website, category) values ('REDAL', '0000', 'REDAL SERVICE', 'http://localhost:8080/redal_logo.jpg','https://redal.com','1');
insert into biller (biller_name, biller_code, biller_description, logo_path, website, category) values ('ORANGE', '0002', 'Recharge telephonique', 'http://localhost:8080/orange-logo.png','https://orange.com','2');
insert into biller (biller_name, biller_code, biller_description, logo_path, website, category) values ('ORANGE', '0006', 'Paiement de facture', 'http://localhost:8080/orange-logo.png','https://orange.com','2');
insert into biller (biller_name, biller_code, biller_description, logo_path, website, category) values ('INWI', '0008', 'Recharge telephonique', 'http://localhost:8080/inwi-logo.jpg','https://inwi.com','2');
insert into biller (biller_name, biller_code, biller_description, logo_path, website, category) values ('RAM', '0007', 'Achat Ticket Avion', 'http://localhost:8080/ram-logo.png','https://ram.com','3');
insert into biller (biller_name, biller_code, biller_description, logo_path, website, category) values ('ONCF', '0003', 'Achat Ticket de Train', 'http://localhost:8080/oncf-logo.png','https://oncf.com','3');
insert into biller (biller_name, biller_code, biller_description, logo_path, website, category) values ('DGI', '0001', 'Paiement Impots', 'http://localhost:8080/dgi-logo.jpg','https://dgi.com','4');
insert into biller (biller_name, biller_code, biller_description, logo_path, website, category) values ('MAROC TELECOM', '0009', 'Recharge telephonique', 'http://localhost:8080/maroc-telecom-logo.jpg','https://maroctelecom.com','2');
insert into biller (biller_name, biller_code, biller_description, logo_path, website, category) values ('AMENDIS', '0010', 'AMENDIS SERVICE', 'http://localhost:8080/amendis-logo.jpg','https://amendis.com','1');
insert into biller (biller_name, biller_code, biller_description, logo_path, website, category) values ('ONEE', '0004', 'ONEE SERVICE', 'http://localhost:8080/onee-logo.png','https://onee.com','1');

insert into debt (debt_code, debt_name, active, biller_id) values ('01','Vignette',true,7);
insert into debt (debt_code, debt_name, active, biller_id) values ('02','Impots sur revenu',true,7);
insert into debt (debt_code, debt_name, active, biller_id) values ('03','Impots immobilier',true,7);
insert into debt (debt_code, debt_name, active, biller_id) values ('01','facture mobile',true,3);
insert into debt (debt_code, debt_name, active, biller_id) values ('02','facture fix',false,3);
insert into debt (debt_code, debt_name, active, biller_id) values ('03','facture Internet',true,3);

insert into form_field (field_name, field_type, field_format, min_size, max_size, contrainte) values ('contrat','text','chaine',5,5,1);
insert into form_field (field_name, field_type, list_vals, field_format, min_size, max_size, contrainte) values ('reference','select','AAA;BBB;CCC;DDD','chaine',1,10,1);
insert into form_field (field_name, field_type, list_vals, field_format, min_size, max_size, contrainte) values ('type','checkbox','CH1;CH2;CH3;CH4','chaine',1,4,0);

insert into debt_canal (debt, canal) values (4,'1');
insert into debt_canal (debt, canal) values (4,'2');
insert into debt_canal (debt, canal) values (4,'3');

insert into debt_canal (debt, canal) values (5,'1');
insert into debt_canal (debt, canal) values (5,'2');
insert into debt_canal (debt, canal) values (5,'3');
insert into debt_canal (debt, canal) values (5,'4');

insert into biller_canal (biller, canal) values (1,'1');
insert into biller_canal (biller, canal) values (1,'2');
insert into biller_canal (biller, canal) values (1,'4');
insert into biller_canal (biller, canal) values (2,'1');
insert into biller_canal (biller, canal) values (2,'2');
insert into biller_canal (biller, canal) values (2,'3');
insert into biller_canal (biller, canal) values (2,'4');
insert into biller_canal (biller, canal) values (3,'1');
insert into biller_canal (biller, canal) values (3,'2');
insert into biller_canal (biller, canal) values (3,'3');
insert into biller_canal (biller, canal) values (3,'4');
insert into biller_canal (biller, canal) values (4,'1');
insert into biller_canal (biller, canal) values (4,'2');
insert into biller_canal (biller, canal) values (4,'3');
insert into biller_canal (biller, canal) values (4,'4');
insert into biller_canal (biller, canal) values (5,'1');
insert into biller_canal (biller, canal) values (5,'2');
insert into biller_canal (biller, canal) values (5,'4');
insert into biller_canal (biller, canal) values (6,'1');
insert into biller_canal (biller, canal) values (6,'2');
insert into biller_canal (biller, canal) values (6,'3');
insert into biller_canal (biller, canal) values (6,'4');
insert into biller_canal (biller, canal) values (7,'1');
insert into biller_canal (biller, canal) values (7,'2');
insert into biller_canal (biller, canal) values (7,'3');
insert into biller_canal (biller, canal) values (7,'4');
insert into biller_canal (biller, canal) values (8,'1');
insert into biller_canal (biller, canal) values (8,'2');
insert into biller_canal (biller, canal) values (8,'3');
insert into biller_canal (biller, canal) values (8,'4');
insert into biller_canal (biller, canal) values (9,'1');
insert into biller_canal (biller, canal) values (9,'2');
insert into biller_canal (biller, canal) values (9,'3');
insert into biller_canal (biller, canal) values (9,'4');
insert into biller_canal (biller, canal) values (10,'1');
insert into biller_canal (biller, canal) values (10,'2');
insert into biller_canal (biller, canal) values (10,'3');
insert into biller_canal (biller, canal) values (10,'4');

insert into debt_form_fields (debt_id, form_fields_id) values (4,1);
insert into debt_form_fields (debt_id, form_fields_id) values (4,2);
insert into debt_form_fields (debt_id, form_fields_id) values (4,3);